# Add the "container" label to pull request that changes the `./container` directory
container:
  - changed-files:
    - any-glob-to-any-file: 'container/**/*'

# Add the "source" label to pull request that changes anything but the `./container` directory
source:
  - all:
    - any-glob-to-any-file: '**/*'
    - all-globs-to-all-files: '!container/**/*'
